import { useEffect, useState, useCallback } from "react";
import { invoke } from "@tauri-apps/api/core";
import { Copy, Check, Plus } from "lucide-react";

interface AddressEntry {
  address: string;
  amount: number;
  confirmations: number;
}

export default function Addresses() {
  const [addresses, setAddresses] = useState<AddressEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [copiedAddr, setCopiedAddr] = useState("");
  const [creating, setCreating] = useState(false);

  const refresh = useCallback(async () => {
    try {
      const result = await invoke<any[]>("wallet_list_addresses");
      setAddresses(
        result
          .map((r) => ({ address: r.address, amount: r.amount, confirmations: r.confirmations }))
          .sort((a, b) => b.amount - a.amount)
      );
    } catch {
      /* wallet not ready yet */
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  async function handleCopy(addr: string) {
    navigator.clipboard.writeText(addr);
    setCopiedAddr(addr);
    setTimeout(() => setCopiedAddr(""), 1500);
  }

  async function handleNewAddress() {
    setCreating(true);
    try {
      await invoke("wallet_get_new_address");
      await refresh();
    } finally {
      setCreating(false);
    }
  }

  return (
    <div className="flex-1 overflow-y-auto px-8 py-6">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-white">Addresses</h1>
          <p className="text-sm text-slate-500">All receiving addresses generated by this wallet</p>
        </div>
        <button
          onClick={handleNewAddress}
          disabled={creating}
          className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-500 disabled:opacity-50"
        >
          <Plus size={15} /> New Address
        </button>
      </div>

      <div className="rounded-2xl border border-white/5 bg-[#111726]">
        {loading ? (
          <div className="py-16 text-center text-sm text-slate-500">Loading...</div>
        ) : addresses.length === 0 ? (
          <div className="py-16 text-center text-sm text-slate-500">No addresses yet</div>
        ) : (
          addresses.map((a) => (
            <div
              key={a.address}
              className="flex items-center justify-between border-b border-white/5 px-4 py-3.5 last:border-0"
            >
              <div className="flex items-center gap-2">
                <span className="font-mono text-sm text-slate-200">{a.address}</span>
                <button onClick={() => handleCopy(a.address)} className="text-slate-500 hover:text-white">
                  {copiedAddr === a.address ? (
                    <Check size={14} className="text-emerald-400" />
                  ) : (
                    <Copy size={14} />
                  )}
                </button>
              </div>
              <span className="text-sm font-medium text-white">
                {a.amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} CIVIC
              </span>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
